### ISSUE TITLE
Index 페이지 PC 버전 (laptop, 1024px~) 마크업

### ISSUE THREAD

**Issue by RED-BENA** [RED-BENA/Kakao-Bank#9]
laptop 사이즈 (1024px) 부터 PC 버전으로 바뀔 수 있도록 한다.

- [x] Header

- [x] Banner

- [x] Section1 (모바일로 더 손쉬운 계좌개설, 간편한 이체)

- [x] Section2 (간편 해외송금, 파격적인 수수료, 애니메이션 세부사항 #11)

- [x] Section3 (우대조건 없이 합리적인 예금과 적금, 애니메이션 세부사항 #11)

- [x] Section4 (서류 제출 없는 대출, 내가 원하는 시간에, 애니메이션 세부사항 #10)

- [x] Section5 (프렌즈 체크카드, 내가 고르는 선택의 즐거움, UI 세부사항 #12)

- [x] Section6 (IT 기술로 카카오뱅크를 만들어 갑니다.)

- [x] Footer
